@domain_name = http://localhost:3003
@api_login_endpoint = api/login


### Login route with a valid user credential

POST {{domain_name}}/{{api_login_endpoint}}
Content-Type: application/json

{
    "username": "john",
    "password": "j!@#$"
}