## Create a new user in the database
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "john",
    "name": "John",
    "password": "j!@#$"
}

### Create a new user in the database

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "erick",
    "name": "Erick",
    "password": "Erick1234"
}