POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Silvester",
    "number": "020-019283"
}

###
## Person without a number

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Peter Williams"
}

###
## Person without a name

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": 1
}

###
## Data whose "name" attribute has less than 3 characters (against limitation)

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ab",
    "number": "048-291006"
}

###
## Data whose number attribute triggers a validation error (it is malformatted)

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Samuel Bridal",
    "number": "1t5-wr0ng"
}
