PUT http://localhost:3001/api/persons/64d7dc75a2009e6f3e67adce
Content-Type: application/json

{
    "id": "64d7dc75a2009e6f3e67adce",
    "name": "Anyone here",
    "number": 2023
}

###
# Sent a non-existent person to be updated (response is 404)
PUT http://localhost:3001/api/persons/64d7dc75a2009e6f3e67aaaa
Content-Type: application/json

{
    "id": "64d7dc75a2009e6f3e67aaaa",
    "name": "Non-existent Person",
    "number": 2023
}

###
# Sent a JSON lacking both due number and name (unchanged resource)
PUT http://localhost:3001/api/persons/64d7dc75a2009e6f3e67adce
Content-Type: application/json

{
    "id": "64d7dc75a2009e6f3e67adce"
}
