# fly.toml app configuration file generated for dvd-phonebook on 2023-08-05T11:27:33-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dvd-phonebook"
primary_region = "gru"

[env]
  PORT = "8080" # add this

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
